version: "3.5"

services:
  server:
    build: server
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
