version: '3'

services:
  server:
    build: server
    ports:
      - "3000:3000"
    restart: unless-stopped
    links:
      - database
    depends_on:
      - database
  #  command: [".db/wait-for-postgres.sh", "db:5432", "--", "./main"]

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
